name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_AIRTABLE_API_KEY: ${{ secrets.REACT_APP_AIRTABLE_API_KEY }}
          REACT_APP_MAPBOX_ACESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACESS_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages
          FOLDER: build
